---
- hosts: all
  become: true
  become_method: sudo

  tasks:

# Setup Mysql server 5.6 galera cluster repositories

   - name: import repository key
     apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=BC19DDBA

   - name: add apt repository for mysql-wsrep-5.6 and Galera Cluster
     apt_repository: repo='{{item}}'
       state=present update_cache=yes
     with_items:
        - "deb http://releases.galeracluster.com/mysql-wsrep-5.6/{{ ansible_distribution|lower() }} {{ ansible_distribution_release }} main"
        - "deb http://releases.galeracluster.com/galera-3/{{ ansible_distribution|lower() }} {{ ansible_distribution_release }} main"

   - name: create a preference file for galera repository. 
     shell: 'echo "Package: *\nPin: origin releases.galeracluster.com\nPin-Priority: 1001" > /etc/apt/preferences.d/mysql-galera-cluster.pref'

# Install Mysql and Galera Cluster packages
   
   - name: Update repositories cache and install Mysql and Galera Cluster packages
     apt:
      name: '{{item}}'
      update_cache: yes 
     with_items:
       - galera-3
       - galera-arbitrator-3
       - mysql-wsrep-5.6 
       - rsync 
