---
- hosts: all
  become: true

# Setup Mysql server 5.6 galera cluster repositories

- name: import repository key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=BC19DDBA

- name: add apt repository for mysql-wsrep-5.6
  apt_repository: repo="deb http://releases.galeracluster.com/mysql-wsrep-5.6/{{ ansible_distribution|lower() }} {{ ansible_distribution_release }} main"
    state=present update_cache=yes

- name: add apt repository for Galera Cluster 
  apt_repository: repo="deb http://releases.galeracluster.com/galera-3/{{ ansible_distribution|lower() }} {{ ansible_distribution_release }} main"
    state=present update_cache=yes

